#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ASPNETDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertbrand_name(brand_name instance);
  partial void Updatebrand_name(brand_name instance);
  partial void Deletebrand_name(brand_name instance);
  partial void InsertCartTable(CartTable instance);
  partial void UpdateCartTable(CartTable instance);
  partial void DeleteCartTable(CartTable instance);
  partial void Insertcategory(category instance);
  partial void Updatecategory(category instance);
  partial void Deletecategory(category instance);
  partial void InsertFeature(Feature instance);
  partial void UpdateFeature(Feature instance);
  partial void DeleteFeature(Feature instance);
  partial void InsertFeedback_table(Feedback_table instance);
  partial void UpdateFeedback_table(Feedback_table instance);
  partial void DeleteFeedback_table(Feedback_table instance);
  partial void Insertmobile_name(mobile_name instance);
  partial void Updatemobile_name(mobile_name instance);
  partial void Deletemobile_name(mobile_name instance);
  partial void InsertPaymentTable(PaymentTable instance);
  partial void UpdatePaymentTable(PaymentTable instance);
  partial void DeletePaymentTable(PaymentTable instance);
  partial void InsertSystemTable(SystemTable instance);
  partial void UpdateSystemTable(SystemTable instance);
  partial void DeleteSystemTable(SystemTable instance);
  partial void InsertOrderTable(OrderTable instance);
  partial void UpdateOrderTable(OrderTable instance);
  partial void DeleteOrderTable(OrderTable instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ASPNETDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<brand_name> brand_names
	{
		get
		{
			return this.GetTable<brand_name>();
		}
	}
	
	public System.Data.Linq.Table<CartTable> CartTables
	{
		get
		{
			return this.GetTable<CartTable>();
		}
	}
	
	public System.Data.Linq.Table<category> categories
	{
		get
		{
			return this.GetTable<category>();
		}
	}
	
	public System.Data.Linq.Table<Feature> Features
	{
		get
		{
			return this.GetTable<Feature>();
		}
	}
	
	public System.Data.Linq.Table<Feedback_table> Feedback_tables
	{
		get
		{
			return this.GetTable<Feedback_table>();
		}
	}
	
	public System.Data.Linq.Table<mobile_name> mobile_names
	{
		get
		{
			return this.GetTable<mobile_name>();
		}
	}
	
	public System.Data.Linq.Table<PaymentTable> PaymentTables
	{
		get
		{
			return this.GetTable<PaymentTable>();
		}
	}
	
	public System.Data.Linq.Table<SystemTable> SystemTables
	{
		get
		{
			return this.GetTable<SystemTable>();
		}
	}
	
	public System.Data.Linq.Table<OrderTable> OrderTables
	{
		get
		{
			return this.GetTable<OrderTable>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[brand name]")]
public partial class brand_name : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _brandid;
	
	private string _brandname;
	
	private string _logo;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbrandidChanging(int value);
    partial void OnbrandidChanged();
    partial void OnbrandnameChanging(string value);
    partial void OnbrandnameChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    #endregion
	
	public brand_name()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brandid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int brandid
	{
		get
		{
			return this._brandid;
		}
		set
		{
			if ((this._brandid != value))
			{
				this.OnbrandidChanging(value);
				this.SendPropertyChanging();
				this._brandid = value;
				this.SendPropertyChanged("brandid");
				this.OnbrandidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brandname", DbType="VarChar(50)")]
	public string brandname
	{
		get
		{
			return this._brandname;
		}
		set
		{
			if ((this._brandname != value))
			{
				this.OnbrandnameChanging(value);
				this.SendPropertyChanging();
				this._brandname = value;
				this.SendPropertyChanged("brandname");
				this.OnbrandnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarChar(50)")]
	public string logo
	{
		get
		{
			return this._logo;
		}
		set
		{
			if ((this._logo != value))
			{
				this.OnlogoChanging(value);
				this.SendPropertyChanging();
				this._logo = value;
				this.SendPropertyChanged("logo");
				this.OnlogoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CartTable")]
public partial class CartTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _CartId;
	
	private System.Nullable<int> _MobileId;
	
	private System.Nullable<int> _Quantity;
	
	private System.Nullable<int> _Amount;
	
	private string _Status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCartIdChanging(System.Nullable<int> value);
    partial void OnCartIdChanged();
    partial void OnMobileIdChanging(System.Nullable<int> value);
    partial void OnMobileIdChanged();
    partial void OnQuantityChanging(System.Nullable<int> value);
    partial void OnQuantityChanged();
    partial void OnAmountChanging(System.Nullable<int> value);
    partial void OnAmountChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
	
	public CartTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CartId", DbType="Int")]
	public System.Nullable<int> CartId
	{
		get
		{
			return this._CartId;
		}
		set
		{
			if ((this._CartId != value))
			{
				this.OnCartIdChanging(value);
				this.SendPropertyChanging();
				this._CartId = value;
				this.SendPropertyChanged("CartId");
				this.OnCartIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileId", DbType="Int")]
	public System.Nullable<int> MobileId
	{
		get
		{
			return this._MobileId;
		}
		set
		{
			if ((this._MobileId != value))
			{
				this.OnMobileIdChanging(value);
				this.SendPropertyChanging();
				this._MobileId = value;
				this.SendPropertyChanged("MobileId");
				this.OnMobileIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
	public System.Nullable<int> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
	public System.Nullable<int> Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _categoryid;
	
	private string _categoryname;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncategoryidChanging(int value);
    partial void OncategoryidChanged();
    partial void OncategorynameChanging(string value);
    partial void OncategorynameChanged();
    #endregion
	
	public category()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int categoryid
	{
		get
		{
			return this._categoryid;
		}
		set
		{
			if ((this._categoryid != value))
			{
				this.OncategoryidChanging(value);
				this.SendPropertyChanging();
				this._categoryid = value;
				this.SendPropertyChanged("categoryid");
				this.OncategoryidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryname", DbType="VarChar(50)")]
	public string categoryname
	{
		get
		{
			return this._categoryname;
		}
		set
		{
			if ((this._categoryname != value))
			{
				this.OncategorynameChanging(value);
				this.SendPropertyChanging();
				this._categoryname = value;
				this.SendPropertyChanged("categoryname");
				this.OncategorynameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Features")]
public partial class Feature : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _featuresid;
	
	private string _Name;
	
	private string _Body;
	
	private string _Display;
	
	private string _OS;
	
	private string _Battery;
	
	private string _Camera;
	
	private string _Weight;
	
	private string _Category;
	
	private string _Brand;
	
	private string _Mobile;
	
	private string _Network;
	
	private string _Sim;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfeaturesidChanging(int value);
    partial void OnfeaturesidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnDisplayChanging(string value);
    partial void OnDisplayChanged();
    partial void OnOSChanging(string value);
    partial void OnOSChanged();
    partial void OnBatteryChanging(string value);
    partial void OnBatteryChanged();
    partial void OnCameraChanging(string value);
    partial void OnCameraChanged();
    partial void OnWeightChanging(string value);
    partial void OnWeightChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnBrandChanging(string value);
    partial void OnBrandChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnNetworkChanging(string value);
    partial void OnNetworkChanged();
    partial void OnSimChanging(string value);
    partial void OnSimChanged();
    #endregion
	
	public Feature()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_featuresid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int featuresid
	{
		get
		{
			return this._featuresid;
		}
		set
		{
			if ((this._featuresid != value))
			{
				this.OnfeaturesidChanging(value);
				this.SendPropertyChanging();
				this._featuresid = value;
				this.SendPropertyChanged("featuresid");
				this.OnfeaturesidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="VarChar(MAX)")]
	public string Body
	{
		get
		{
			return this._Body;
		}
		set
		{
			if ((this._Body != value))
			{
				this.OnBodyChanging(value);
				this.SendPropertyChanging();
				this._Body = value;
				this.SendPropertyChanged("Body");
				this.OnBodyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Display", DbType="VarChar(MAX)")]
	public string Display
	{
		get
		{
			return this._Display;
		}
		set
		{
			if ((this._Display != value))
			{
				this.OnDisplayChanging(value);
				this.SendPropertyChanging();
				this._Display = value;
				this.SendPropertyChanged("Display");
				this.OnDisplayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OS", DbType="VarChar(50)")]
	public string OS
	{
		get
		{
			return this._OS;
		}
		set
		{
			if ((this._OS != value))
			{
				this.OnOSChanging(value);
				this.SendPropertyChanging();
				this._OS = value;
				this.SendPropertyChanged("OS");
				this.OnOSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Battery", DbType="VarChar(MAX)")]
	public string Battery
	{
		get
		{
			return this._Battery;
		}
		set
		{
			if ((this._Battery != value))
			{
				this.OnBatteryChanging(value);
				this.SendPropertyChanging();
				this._Battery = value;
				this.SendPropertyChanged("Battery");
				this.OnBatteryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Camera", DbType="VarChar(MAX)")]
	public string Camera
	{
		get
		{
			return this._Camera;
		}
		set
		{
			if ((this._Camera != value))
			{
				this.OnCameraChanging(value);
				this.SendPropertyChanging();
				this._Camera = value;
				this.SendPropertyChanged("Camera");
				this.OnCameraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="VarChar(50)")]
	public string Weight
	{
		get
		{
			return this._Weight;
		}
		set
		{
			if ((this._Weight != value))
			{
				this.OnWeightChanging(value);
				this.SendPropertyChanging();
				this._Weight = value;
				this.SendPropertyChanged("Weight");
				this.OnWeightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(50)")]
	public string Category
	{
		get
		{
			return this._Category;
		}
		set
		{
			if ((this._Category != value))
			{
				this.OnCategoryChanging(value);
				this.SendPropertyChanging();
				this._Category = value;
				this.SendPropertyChanged("Category");
				this.OnCategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="VarChar(50)")]
	public string Brand
	{
		get
		{
			return this._Brand;
		}
		set
		{
			if ((this._Brand != value))
			{
				this.OnBrandChanging(value);
				this.SendPropertyChanging();
				this._Brand = value;
				this.SendPropertyChanged("Brand");
				this.OnBrandChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
	public string Mobile
	{
		get
		{
			return this._Mobile;
		}
		set
		{
			if ((this._Mobile != value))
			{
				this.OnMobileChanging(value);
				this.SendPropertyChanging();
				this._Mobile = value;
				this.SendPropertyChanged("Mobile");
				this.OnMobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Network", DbType="VarChar(MAX)")]
	public string Network
	{
		get
		{
			return this._Network;
		}
		set
		{
			if ((this._Network != value))
			{
				this.OnNetworkChanging(value);
				this.SendPropertyChanging();
				this._Network = value;
				this.SendPropertyChanged("Network");
				this.OnNetworkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sim", DbType="VarChar(MAX)")]
	public string Sim
	{
		get
		{
			return this._Sim;
		}
		set
		{
			if ((this._Sim != value))
			{
				this.OnSimChanging(value);
				this.SendPropertyChanging();
				this._Sim = value;
				this.SendPropertyChanged("Sim");
				this.OnSimChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Feedback table]")]
public partial class Feedback_table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _firstname;
	
	private string _lastname;
	
	private string _email;
	
	private System.Nullable<decimal> _mobile;
	
	private string _message;
	
	private string _status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmobileChanging(System.Nullable<decimal> value);
    partial void OnmobileChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public Feedback_table()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(50)")]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this.OnfirstnameChanging(value);
				this.SendPropertyChanging();
				this._firstname = value;
				this.SendPropertyChanged("firstname");
				this.OnfirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(50)")]
	public string lastname
	{
		get
		{
			return this._lastname;
		}
		set
		{
			if ((this._lastname != value))
			{
				this.OnlastnameChanging(value);
				this.SendPropertyChanging();
				this._lastname = value;
				this.SendPropertyChanged("lastname");
				this.OnlastnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(MAX)")]
	public string message
	{
		get
		{
			return this._message;
		}
		set
		{
			if ((this._message != value))
			{
				this.OnmessageChanging(value);
				this.SendPropertyChanging();
				this._message = value;
				this.SendPropertyChanged("message");
				this.OnmessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[mobile name]")]
public partial class mobile_name : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _mobileid;
	
	private System.Nullable<int> _categoryid;
	
	private System.Nullable<int> _brandid;
	
	private string _mobilename;
	
	private string _description;
	
	private string _image;
	
	private string _price;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmobileidChanging(int value);
    partial void OnmobileidChanged();
    partial void OncategoryidChanging(System.Nullable<int> value);
    partial void OncategoryidChanged();
    partial void OnbrandidChanging(System.Nullable<int> value);
    partial void OnbrandidChanged();
    partial void OnmobilenameChanging(string value);
    partial void OnmobilenameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnpriceChanging(string value);
    partial void OnpriceChanged();
    #endregion
	
	public mobile_name()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobileid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int mobileid
	{
		get
		{
			return this._mobileid;
		}
		set
		{
			if ((this._mobileid != value))
			{
				this.OnmobileidChanging(value);
				this.SendPropertyChanging();
				this._mobileid = value;
				this.SendPropertyChanged("mobileid");
				this.OnmobileidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryid", DbType="Int")]
	public System.Nullable<int> categoryid
	{
		get
		{
			return this._categoryid;
		}
		set
		{
			if ((this._categoryid != value))
			{
				this.OncategoryidChanging(value);
				this.SendPropertyChanging();
				this._categoryid = value;
				this.SendPropertyChanged("categoryid");
				this.OncategoryidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brandid", DbType="Int")]
	public System.Nullable<int> brandid
	{
		get
		{
			return this._brandid;
		}
		set
		{
			if ((this._brandid != value))
			{
				this.OnbrandidChanging(value);
				this.SendPropertyChanging();
				this._brandid = value;
				this.SendPropertyChanged("brandid");
				this.OnbrandidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobilename", DbType="VarChar(MAX)")]
	public string mobilename
	{
		get
		{
			return this._mobilename;
		}
		set
		{
			if ((this._mobilename != value))
			{
				this.OnmobilenameChanging(value);
				this.SendPropertyChanging();
				this._mobilename = value;
				this.SendPropertyChanged("mobilename");
				this.OnmobilenameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(50)")]
	public string image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="VarChar(50)")]
	public string price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentTable")]
public partial class PaymentTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Paymentid;
	
	private System.Nullable<int> _OrderId;
	
	private System.Nullable<decimal> _Amount;
	
	private string _CardType;
	
	private string _Name;
	
	private System.Nullable<decimal> _CardNumber;
	
	private string _ExpDate;
	
	private string _cvc;
	
	private string _Status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaymentidChanging(int value);
    partial void OnPaymentidChanged();
    partial void OnOrderIdChanging(System.Nullable<int> value);
    partial void OnOrderIdChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnCardTypeChanging(string value);
    partial void OnCardTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCardNumberChanging(System.Nullable<decimal> value);
    partial void OnCardNumberChanged();
    partial void OnExpDateChanging(string value);
    partial void OnExpDateChanged();
    partial void OncvcChanging(string value);
    partial void OncvcChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
	
	public PaymentTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paymentid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Paymentid
	{
		get
		{
			return this._Paymentid;
		}
		set
		{
			if ((this._Paymentid != value))
			{
				this.OnPaymentidChanging(value);
				this.SendPropertyChanging();
				this._Paymentid = value;
				this.SendPropertyChanged("Paymentid");
				this.OnPaymentidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="Int")]
	public System.Nullable<int> OrderId
	{
		get
		{
			return this._OrderId;
		}
		set
		{
			if ((this._OrderId != value))
			{
				this.OnOrderIdChanging(value);
				this.SendPropertyChanging();
				this._OrderId = value;
				this.SendPropertyChanged("OrderId");
				this.OnOrderIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardType", DbType="VarChar(50)")]
	public string CardType
	{
		get
		{
			return this._CardType;
		}
		set
		{
			if ((this._CardType != value))
			{
				this.OnCardTypeChanging(value);
				this.SendPropertyChanging();
				this._CardType = value;
				this.SendPropertyChanged("CardType");
				this.OnCardTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNumber", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> CardNumber
	{
		get
		{
			return this._CardNumber;
		}
		set
		{
			if ((this._CardNumber != value))
			{
				this.OnCardNumberChanging(value);
				this.SendPropertyChanging();
				this._CardNumber = value;
				this.SendPropertyChanged("CardNumber");
				this.OnCardNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="VarChar(50)")]
	public string ExpDate
	{
		get
		{
			return this._ExpDate;
		}
		set
		{
			if ((this._ExpDate != value))
			{
				this.OnExpDateChanging(value);
				this.SendPropertyChanging();
				this._ExpDate = value;
				this.SendPropertyChanged("ExpDate");
				this.OnExpDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvc", DbType="VarChar(50)")]
	public string cvc
	{
		get
		{
			return this._cvc;
		}
		set
		{
			if ((this._cvc != value))
			{
				this.OncvcChanging(value);
				this.SendPropertyChanging();
				this._cvc = value;
				this.SendPropertyChanged("cvc");
				this.OncvcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SystemTable")]
public partial class SystemTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _systemid;
	
	private System.Nullable<int> _imageid;
	
	private System.Nullable<int> _cartid;
	
	private System.Nullable<int> _orderid;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsystemidChanging(int value);
    partial void OnsystemidChanged();
    partial void OnimageidChanging(System.Nullable<int> value);
    partial void OnimageidChanged();
    partial void OncartidChanging(System.Nullable<int> value);
    partial void OncartidChanged();
    partial void OnorderidChanging(System.Nullable<int> value);
    partial void OnorderidChanged();
    #endregion
	
	public SystemTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_systemid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int systemid
	{
		get
		{
			return this._systemid;
		}
		set
		{
			if ((this._systemid != value))
			{
				this.OnsystemidChanging(value);
				this.SendPropertyChanging();
				this._systemid = value;
				this.SendPropertyChanged("systemid");
				this.OnsystemidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageid", DbType="Int")]
	public System.Nullable<int> imageid
	{
		get
		{
			return this._imageid;
		}
		set
		{
			if ((this._imageid != value))
			{
				this.OnimageidChanging(value);
				this.SendPropertyChanging();
				this._imageid = value;
				this.SendPropertyChanged("imageid");
				this.OnimageidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cartid", DbType="Int")]
	public System.Nullable<int> cartid
	{
		get
		{
			return this._cartid;
		}
		set
		{
			if ((this._cartid != value))
			{
				this.OncartidChanging(value);
				this.SendPropertyChanging();
				this._cartid = value;
				this.SendPropertyChanged("cartid");
				this.OncartidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderid", DbType="Int")]
	public System.Nullable<int> orderid
	{
		get
		{
			return this._orderid;
		}
		set
		{
			if ((this._orderid != value))
			{
				this.OnorderidChanging(value);
				this.SendPropertyChanging();
				this._orderid = value;
				this.SendPropertyChanged("orderid");
				this.OnorderidChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderTable")]
public partial class OrderTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Orderid;
	
	private System.Nullable<int> _Cartid;
	
	private string _Name;
	
	private System.Nullable<decimal> _Mobile;
	
	private string _Email;
	
	private string _Address;
	
	private string _City;
	
	private string _State;
	
	private System.Nullable<int> _ZipCode;
	
	private System.Nullable<int> _totalquantity;
	
	private System.Nullable<int> _totalamount;
	
	private string _PaymentType;
	
	private string _date;
	
	private string _status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderidChanging(int value);
    partial void OnOrderidChanged();
    partial void OnCartidChanging(System.Nullable<int> value);
    partial void OnCartidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMobileChanging(System.Nullable<decimal> value);
    partial void OnMobileChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipCodeChanging(System.Nullable<int> value);
    partial void OnZipCodeChanged();
    partial void OntotalquantityChanging(System.Nullable<int> value);
    partial void OntotalquantityChanged();
    partial void OntotalamountChanging(System.Nullable<int> value);
    partial void OntotalamountChanged();
    partial void OnPaymentTypeChanging(string value);
    partial void OnPaymentTypeChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public OrderTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orderid", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Orderid
	{
		get
		{
			return this._Orderid;
		}
		set
		{
			if ((this._Orderid != value))
			{
				this.OnOrderidChanging(value);
				this.SendPropertyChanging();
				this._Orderid = value;
				this.SendPropertyChanged("Orderid");
				this.OnOrderidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cartid", DbType="Int")]
	public System.Nullable<int> Cartid
	{
		get
		{
			return this._Cartid;
		}
		set
		{
			if ((this._Cartid != value))
			{
				this.OnCartidChanging(value);
				this.SendPropertyChanging();
				this._Cartid = value;
				this.SendPropertyChanged("Cartid");
				this.OnCartidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(10)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Mobile
	{
		get
		{
			return this._Mobile;
		}
		set
		{
			if ((this._Mobile != value))
			{
				this.OnMobileChanging(value);
				this.SendPropertyChanging();
				this._Mobile = value;
				this.SendPropertyChanged("Mobile");
				this.OnMobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="Int")]
	public System.Nullable<int> ZipCode
	{
		get
		{
			return this._ZipCode;
		}
		set
		{
			if ((this._ZipCode != value))
			{
				this.OnZipCodeChanging(value);
				this.SendPropertyChanging();
				this._ZipCode = value;
				this.SendPropertyChanged("ZipCode");
				this.OnZipCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalquantity", DbType="Int")]
	public System.Nullable<int> totalquantity
	{
		get
		{
			return this._totalquantity;
		}
		set
		{
			if ((this._totalquantity != value))
			{
				this.OntotalquantityChanging(value);
				this.SendPropertyChanging();
				this._totalquantity = value;
				this.SendPropertyChanged("totalquantity");
				this.OntotalquantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalamount", DbType="Int")]
	public System.Nullable<int> totalamount
	{
		get
		{
			return this._totalamount;
		}
		set
		{
			if ((this._totalamount != value))
			{
				this.OntotalamountChanging(value);
				this.SendPropertyChanging();
				this._totalamount = value;
				this.SendPropertyChanged("totalamount");
				this.OntotalamountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", DbType="VarChar(50)")]
	public string PaymentType
	{
		get
		{
			return this._PaymentType;
		}
		set
		{
			if ((this._PaymentType != value))
			{
				this.OnPaymentTypeChanging(value);
				this.SendPropertyChanging();
				this._PaymentType = value;
				this.SendPropertyChanged("PaymentType");
				this.OnPaymentTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="VarChar(50)")]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
