<?xml version="1.0" encoding="utf-8"?><Database Name="ASPNETDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\ASPNETDB.MDF;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ASPNETDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[brand name]" Member="brand_names">
    <Type Name="brand_name">
      <Column Name="brandid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="brandname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CartTable" Member="CartTables">
    <Type Name="CartTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CartId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MobileId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="categoryid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="categoryname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Features" Member="Features">
    <Type Name="Feature">
      <Column Name="featuresid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Display" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="OS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Battery" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Camera" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Network" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sim" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Feedback table]" Member="Feedback_tables">
    <Type Name="Feedback_table">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mobile" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[mobile name]" Member="mobile_names">
    <Type Name="mobile_name">
      <Column Name="mobileid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="categoryid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="brandid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mobilename" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentTable" Member="PaymentTables">
    <Type Name="PaymentTable">
      <Column Name="Paymentid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CardType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CardNumber" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ExpDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cvc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SystemTable" Member="SystemTables">
    <Type Name="SystemTable">
      <Column Name="systemid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="imageid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cartid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="orderid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderTable" Member="OrderTables">
    <Type Name="OrderTable">
      <Column Name="Orderid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cartid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="totalquantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="totalamount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>